# Generated by Django 3.1.7 on 2021-03-21 22:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import timewebapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimewebModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_sel', models.CharField(max_length=100, verbose_name='Enter the Name of this Assignment')),
                ('ad', models.DateField(null=True, verbose_name='Enter the Assignment Date')),
                ('x', models.DateField(blank=True, null=True, verbose_name='Enter the Due Date')),
                ('unit', models.CharField(default='Minute', max_length=40, verbose_name='Enter the Name of each Unit of Work')),
                ('y', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1, 'This value cannot be less than %(limit_value)s')], verbose_name='Enter the Total amount of Units in this Assignment')),
                ('works', models.JSONField(default=timewebapp.models.default_works, verbose_name='Enter the Total amount of Units already Completed')),
                ('dif_assign', models.IntegerField(blank=True, null=True)),
                ('skew_ratio', models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True, verbose_name='Enter the Estimated amount of Time to complete each Unit of Work in Minutes')),
                ('ctime', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), 'This value must be positive')], verbose_name='Enter the Estimated amount of Time to complete each Unit of Work in Minutes')),
                ('funct_round', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), 'The grouping value must be positive')], verbose_name='Enter the Grouping Value')),
                ('min_work_time', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), 'The minimum work time must be positive')], verbose_name='Enter the Minimum Work Time per Day in Minutes')),
                ('nwd', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=13, null=True)),
                ('fixed_mode', models.BooleanField(default=False)),
                ('dynamic_start', models.IntegerField(blank=True, null=True)),
                ('remainder_mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
