# Generated by Django 3.1.3 on 2020-11-27 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='img',
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
