# Generated by Django 3.1.7 on 2021-04-07 02:42

import django.core.validators
from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateField(null=True, verbose_name='Assignment Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, 'This value must be positive')], verbose_name='Estimated amount of Time to complete each Unit of Work in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=100, verbose_name='Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='fixed_mode',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, 'This value must be positive')], verbose_name='Number of Units you will Work at a Time'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, 'The minimum work time must be positive')], verbose_name='Minimum Work Time per Day in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='remainder_mode',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='skew_ratio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True, verbose_name='Estimated amount of Time to complete each Unit of Work in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', max_length=40, verbose_name='Name of each Unit of Work'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works, verbose_name='Total number of Units already Completed'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1, 'This value cannot be less than %(limit_value)s')], verbose_name='Total number of Units in this Assignment'),
        ),
    ]
