# Generated by Django 3.2.10 on 2022-01-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='one_graph_at_a_time',
            field=models.BooleanField(default=False, verbose_name='Allow Only One Open Graph at a Time'),
        ),
    ]
