# Generated by Django 3.2.7 on 2021-11-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimewebUser',
        ),
    ]
