# Generated by Django 3.2.12 on 2022-02-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
