# Generated by Django 3.1.7 on 2021-04-08 06:47

import django.core.validators
from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0002_auto_20210406_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, 'This value must be positive')]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, 'This value must be positive')]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='skew_ratio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1, 'This value cannot be less than %(limit_value)s')]),
        ),
    ]
