# Generated by Django 3.1.3 on 2020-12-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0002_auto_20201127_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='last_modified',
        ),
    ]
