# Generated by Django 3.1.3 on 2021-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0003_remove_timewebmodel_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
