# Generated by Django 3.2.11 on 2022-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0003_remove_settingsmodel_use_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='color_priority',
        ),
        migrations.RemoveField(
            model_name='settingsmodel',
            name='text_priority',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='show_priority',
            field=models.BooleanField(default=True, verbose_name='Show Priority'),
        ),
    ]
