# Generated by Django 3.1.3 on 2021-03-01 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0003_auto_20210228_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timewebapp.user'),
        ),
    ]
