# Generated by Django 3.2.12 on 2022-03-07 09:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0003_auto_20220306_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_break_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Mon'), ('2', 'Tue'), ('3', 'Wed'), ('4', 'Thu'), ('5', 'Fri'), ('6', 'Sat'), ('0', 'Sun')], max_length=13, null=True, verbose_name='Default Work Days'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='break_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Mon'), ('2', 'Tue'), ('3', 'Wed'), ('4', 'Thu'), ('5', 'Fri'), ('6', 'Sat'), ('0', 'Sun')], max_length=13, null=True, verbose_name='Working Days'),
        ),
    ]
