# Generated by Django 3.1.3 on 2021-01-25 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0004_auto_20210125_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='timewebmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timewebmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='adone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='ctime',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(blank=True, max_length=40, verbose_name='Name: '),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='x',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='nwd',
            field=models.ManyToManyField(to='timewebapp.Days'),
        ),
    ]
