# Generated by Django 3.2.12 on 2022-03-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0004_auto_20220307_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='def_unit_to_minute',
        ),
    ]
