# Generated by Django 3.2.12 on 2022-02-15 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0004_auto_20220201_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='due_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
