# Generated by Django 3.2.12 on 2022-03-08 17:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0005_remove_settingsmodel_def_unit_to_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'The default minimum work time must be positive or zero')], verbose_name='Default Minimum Daily Work Time'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'The minimum work time must be positive or zero')], verbose_name='Minimum Daily Work Time'),
        ),
    ]
