# Generated by Django 3.2.12 on 2022-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0005_alter_timewebmodel_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='due_time',
            field=models.TimeField(null=True),
        ),
    ]
