# Generated by Django 3.1.3 on 2021-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0005_auto_20210125_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateField(null=True),
        ),
    ]
