# Generated by Django 3.1.8 on 2021-04-09 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0005_auto_20210409_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='warning_acceptance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, 'This value must be any integer from 1-100'), django.core.validators.MaxValueValidator(100, 'This value must be any integer from 1-100')]),
        ),
    ]
