# Generated by Django 3.1.3 on 2021-01-25 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0006_auto_20210125_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='nwd',
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='nwd',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
