# Generated by Django 3.2.12 on 2022-03-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0006_auto_20220308_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='show_progress_bar',
        ),
    ]
