# Generated by Django 3.1.3 on 2021-03-04 08:28

import django.core.validators
from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0007_auto_20210303_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateField(null=True, verbose_name='Enter the Assignment Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Enter the Estimated amount of Time to complete each Unit of Work in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=100, verbose_name='Enter the Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', max_length=40, verbose_name='Enter the Name of each Unit of Work'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works, verbose_name='Enter the Total amount of Units already Completed'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Enter the Total amount of Units'),
        ),
    ]
