# Generated by Django 3.1.3 on 2021-01-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0007_auto_20210125_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='nwd',
        ),
    ]
