# Generated by Django 3.2.12 on 2022-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0007_remove_settingsmodel_show_progress_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='enable_tutorial',
            field=models.BooleanField(default=True, verbose_name='Tutorial'),
        ),
    ]
