# Generated by Django 3.1.3 on 2021-03-04 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0008_auto_20210304_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Enter the Assignment Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Enter the Due Date'),
        ),
    ]
