# Generated by Django 3.1.8 on 2021-04-10 03:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0008_auto_20210409_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'The default minimum work time must be positive')], verbose_name='Default Minimum Daily Work Time in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'The minimum work time must be positive')], verbose_name='Minimum Daily Work Time in Minutes'),
        ),
    ]
