# Generated by Django 3.1.3 on 2021-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0009_auto_20210125_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='nwd',
            field=models.CharField(choices=[('0', 'SUNDAY'), ('1', 'MONDAY'), ('2', 'TUESDAY'), ('3', 'WEDNESDAY'), ('4', 'THURSDAY'), ('5', 'FRIDAY'), ('6', 'SATURDAY')], default=4, max_length=2),
            preserve_default=False,
        ),
    ]
