# Generated by Django 3.2.12 on 2022-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0009_remove_settingsmodel_assignment_spacing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsModel',
        ),
    ]
