# Generated by Django 3.1.3 on 2021-03-04 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0009_auto_20210304_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enter the Assignment Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Enter the Due Date'),
        ),
    ]
