# Generated by Django 3.1.3 on 2021-01-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0010_timewebmodel_nwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='adone',
            new_name='works',
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='dif_assign',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='dynamic_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='fixed_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='remainder_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='skew_ratio',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='timewebmodel',
            name='total_mode',
            field=models.BooleanField(default=False),
        ),
    ]
