# Generated by Django 3.1.3 on 2021-03-07 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0011_auto_20210304_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, 'This value must be positive')], verbose_name='Enter the Estimated amount of Time to complete each Unit of Work in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, 'The grouping value must be positive')], verbose_name='Enter the Grouping Value'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, 'The minimum work time must be positive')], verbose_name='Enter the Minimum Work Time per Day in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0, 'This value cannot be less than %(limit_value)s')], verbose_name='Enter the Total amount of Units'),
        ),
    ]
