# Generated by Django 3.1.8 on 2021-04-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0011_auto_20210416_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='defnwd',
            new_name='def_nwd',
        ),
    ]
