# Generated by Django 3.1.3 on 2021-01-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0011_auto_20210125_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='works',
            new_name='adone',
        ),
    ]
