# Generated by Django 3.2.13 on 2022-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0011_alter_timewebmodel_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='google_classroom_assignment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
