# Generated by Django 4.0.6 on 2022-07-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0012_timewebmodel_google_classroom_assignment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='mark_as_done',
        ),
    ]
