# Generated by Django 3.1.3 on 2021-03-09 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0012_auto_20210306_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='skew_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Enter the Estimated amount of Time to complete each Unit of Work in Minutes'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0, 'This value cannot be less than %(limit_value)s')], verbose_name='Enter the Total amount of Units in this Assignment'),
        ),
    ]
