# Generated by Django 3.1.8 on 2021-04-17 07:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0012_auto_20210416_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_nwd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=13, null=True),
        ),
    ]
