# Generated by Django 3.1.8 on 2021-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0013_auto_20210417_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_skew_ratio',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=17, verbose_name='Default Skew Ratio'),
        ),
    ]
