# Generated by Django 3.2.13 on 2022-07-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0013_remove_timewebmodel_mark_as_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
