# Generated by Django 3.1.3 on 2021-01-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0014_auto_20210126_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='dif_assign',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
