# Generated by Django 3.2.13 on 2022-07-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0014_timewebmodel_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='dont_hide_again',
            field=models.BooleanField(default=False),
        ),
    ]
