# Generated by Django 3.1.8 on 2021-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0014_auto_20210417_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='first_visit',
            field=models.BooleanField(default=False),
        ),
    ]
