# Generated by Django 4.0.7 on 2022-09-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0015_timewebmodel_dont_hide_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
