# Generated by Django 3.1.8 on 2021-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0015_timewebmodel_first_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='first_visit',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='first_visit',
            field=models.BooleanField(default=False),
        ),
    ]
