# Generated by Django 4.0.7 on 2022-09-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0016_timewebmodel_deleted_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='deleted_time',
            new_name='deletion_time',
        ),
    ]
