# Generated by Django 3.1.3 on 2021-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0016_auto_20210126_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.IntegerField(null=True),
        ),
    ]
