# Generated by Django 3.1.3 on 2021-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0017_auto_20210126_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='adone',
            new_name='works',
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateField(null=True),
        ),
    ]
