# Generated by Django 4.1.7 on 2023-02-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0017_rename_deleted_time_timewebmodel_deletion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='has_alerted_due_date_passed_notice',
        ),
    ]
