# Generated by Django 3.1.3 on 2021-01-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0018_auto_20210126_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(),
        ),
    ]
