# Generated by Django 3.1.8 on 2021-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0018_auto_20210417_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_skew_ratio',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=17, verbose_name='Default Skew Ratio'),
        ),
    ]
