# Generated by Django 3.1.3 on 2021-01-27 05:08

from django.db import migrations, models
import multiselectfield.db.fields
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0019_auto_20210126_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='nwd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works),
        ),
    ]
