# Generated by Django 4.1.7 on 2023-04-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0019_rename_google_classroom_assignment_link_timewebmodel_assignment_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='assignment_link',
            new_name='external_link',
        ),
    ]
