# Generated by Django 3.1.3 on 2021-01-27 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0020_auto_20210127_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='skew_ratio',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
