# Generated by Django 4.1.9 on 2023-06-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0021_alter_timewebmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='is_integration_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
