# Generated by Django 3.1.8 on 2021-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0021_auto_20210418_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_info_buttons',
            field=models.BooleanField(default=True, verbose_name='Show Info Buttons'),
        ),
    ]
