# Generated by Django 3.1.3 on 2021-01-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0022_auto_20210127_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.IntegerField(null=True),
        ),
    ]
