# Generated by Django 3.1.8 on 2021-04-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0022_auto_20210418_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='remainder_mode',
        ),
    ]
