# Generated by Django 4.1.9 on 2023-06-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0022_timewebmodel_is_integration_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='is_canvas_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
