# Generated by Django 3.1.3 on 2021-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0023_auto_20210130_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateField(null=True),
        ),
    ]
