# Generated by Django 3.1.8 on 2021-05-04 06:39

import django.core.serializers.json
from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0023_remove_timewebmodel_remainder_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
