# Generated by Django 4.1.9 on 2023-06-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "timewebapp",
            "0024_rename_is_google_classroom_assignment_timewebmodel_is_gc_assignment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timewebmodel",
            name="is_moodle_assignment",
            field=models.BooleanField(default=False),
        ),
    ]
