# Generated by Django 3.1.8 on 2021-05-04 06:42

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0024_auto_20210503_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works),
        ),
    ]
