# Generated by Django 3.1.3 on 2021-01-31 09:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0024_auto_20210130_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='total_mode',
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=40, verbose_name='Name '),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='nwd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')], max_length=13, null=True),
        ),
    ]
