# Generated by Django 3.1.3 on 2021-02-01 04:34

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0025_auto_20210131_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateField(null=True, verbose_name='Enter the Assignment Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='ctime',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Enter the Estimated amount of Time in Minutes to complete each Unit of Work'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=40, verbose_name='Enter the Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='this is a test for help text', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Enter the Grouping Value'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Enter the Minimum Work Time'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='nwd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', max_length=40, verbose_name='Enter the Name of each Unit of Work'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(default=timewebapp.models.default_works, verbose_name='Enter the Total amount of Units already Completed'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateField(null=True, verbose_name='Enter the Due Date'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Enter the Total amount of Units'),
        ),
    ]
