# Generated by Django 3.1.8 on 2021-05-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0025_auto_20210503_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='text_priority',
            field=models.BooleanField(default=True, verbose_name='Display Priority with Text'),
        ),
    ]
