# Generated by Django 3.1.3 on 2021-02-01 23:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0026_auto_20210131_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=100, verbose_name='Enter the Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='funct_round',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), help_text='this is a test for help text, a default of 1 is here for now', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Enter the Grouping Value'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Enter the Minimum Work Time per Day'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', help_text='(Do not make this plural)', max_length=40, verbose_name='Enter the Name of each Unit of Work'),
        ),
    ]
