# Generated by Django 3.1.8 on 2021-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0026_auto_20210504_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='ad',
            field=models.DateField(null=True, verbose_name='Date Assigned'),
        ),
    ]
