# Generated by Django 3.1.8 on 2021-05-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0027_auto_20210505_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
