# Generated by Django 3.1.8 on 2021-05-08 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0028_timewebmodel_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='date_now',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
