# Generated by Django 3.1.8 on 2021-05-08 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0029_timewebmodel_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewebmodel',
            name='date_now',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='date_now',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
