# Generated by Django 3.1.3 on 2021-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0029_auto_20210201_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(error_messages={'invalid': 'Enter a valid phone number'}, max_length=100, verbose_name='Enter the Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', error_messages={'invalid': 'Enter a valid phone number'}, max_length=40, verbose_name='Enter the Name of each Unit of Work'),
        ),
    ]
