# Generated by Django 3.1.3 on 2021-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0030_auto_20210214_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=100, verbose_name='Enter the Name of this Assignment'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(default='Minute', max_length=40, verbose_name='Enter the Name of each Unit of Work'),
        ),
    ]
