# Generated by Django 3.1.8 on 2021-05-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0030_auto_20210508_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='file_sel',
            new_name='assignment_name',
        ),
    ]
