# Generated by Django 3.1.3 on 2021-02-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0031_auto_20210214_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(error_messages={'blank': 'your custom error message'}, max_length=100, unique=True, verbose_name='Enter the Name of this Assignment'),
        ),
    ]
