# Generated by Django 3.1.8 on 2021-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0031_auto_20210508_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='hidden',
            new_name='mark_as_done',
        ),
    ]
