# Generated by Django 3.1.8 on 2021-05-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0032_auto_20210511_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='def_nwd',
            new_name='def_break_days',
        ),
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='nwd',
            new_name='break_days',
        ),
    ]
