# Generated by Django 3.1.8 on 2021-05-23 02:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0033_auto_20210520_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='highest_priority_color',
            field=colorfield.fields.ColorField(default='#e25b50', max_length=18),
        ),
    ]
