# Generated by Django 3.1.3 on 2021-02-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0033_auto_20210214_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(error_messages={'unique': 'An assignment with this name already exists'}, max_length=100, unique=True, verbose_name='Enter the Name of this Assignment'),
        ),
    ]
