# Generated by Django 3.1.3 on 2021-02-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0034_auto_20210214_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='file_sel',
            field=models.CharField(max_length=100, verbose_name='Enter the Name of this Assignment'),
        ),
    ]
