# Generated by Django 3.1.8 on 2021-05-23 03:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0034_settingsmodel_highest_priority_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='lowest_priority_color',
            field=colorfield.fields.ColorField(default='#84c841', max_length=18),
        ),
    ]
