# Generated by Django 3.1.8 on 2021-05-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0035_settingsmodel_lowest_priority_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='show_info_buttons',
        ),
    ]
