# Generated by Django 3.1.8 on 2021-05-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0036_remove_settingsmodel_show_info_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='show_past',
        ),
    ]
