# Generated by Django 3.1.8 on 2021-05-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0037_remove_settingsmodel_show_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='def_unit_to_minute',
            field=models.BooleanField(default=False, verbose_name='Set the Default Unit of Work to "Minute"'),
        ),
    ]
