# Generated by Django 3.1.8 on 2021-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0038_settingsmodel_def_unit_to_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(max_length=40, verbose_name='Name of each Unit of Work'),
        ),
    ]
