# Generated by Django 3.2.4 on 2021-06-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0046_rename_dif_assign_timewebmodel_blue_line_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='ad',
            new_name='assignment_date',
        ),
    ]
