# Generated by Django 3.2.4 on 2021-06-29 18:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0047_rename_ad_timewebmodel_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='color_priority',
            field=models.BooleanField(default=True, verbose_name='Show Priority Colors'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='highest_priority_color',
            field=colorfield.fields.ColorField(default='#e25b50', max_length=18, verbose_name='Highest Priority Color'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='lowest_priority_color',
            field=colorfield.fields.ColorField(default='#84c841', max_length=18, verbose_name='Lowest Priority Color'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='text_priority',
            field=models.BooleanField(default=True, verbose_name='Show Priority Text'),
        ),
    ]
