# Generated by Django 3.2.4 on 2021-07-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0048_auto_20210629_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='first_login',
            new_name='enable_tutorial',
        ),
    ]
