# Generated by Django 3.2.4 on 2021-07-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0050_auto_20210705_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='assignment_date',
            field=models.DateTimeField(null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='x',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
