# Generated by Django 3.2.4 on 2021-07-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0051_auto_20210706_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='date_now',
        ),
    ]
