# Generated by Django 3.2.4 on 2021-07-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0053_auto_20210706_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='needs_more_info',
            field=models.BooleanField(default=False),
        ),
    ]
