# Generated by Django 3.2.4 on 2021-07-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0056_alter_timewebmodel_funct_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='added_gc_assignments',
            new_name='added_gc_assignment_ids',
        ),
    ]
