# Generated by Django 3.2.4 on 2021-07-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0057_rename_added_gc_assignments_settingsmodel_added_gc_assignment_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='assignment_name',
            new_name='name',
        ),
    ]
