# Generated by Django 3.2.4 on 2021-07-08 21:26

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0058_rename_assignment_name_timewebmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='tags',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
    ]
