# Generated by Django 3.2.4 on 2021-07-09 23:15

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0059_alter_timewebmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='oauth_token',
            field=models.JSONField(default=timewebapp.models.empty_dict),
        ),
    ]
