# Generated by Django 3.2.4 on 2021-07-11 07:21

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0060_alter_settingsmodel_oauth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='added_gc_assignment_ids',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='oauth_token',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_dict),
        ),
    ]
