# Generated by Django 3.2.4 on 2021-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0061_auto_20210711_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
