# Generated by Django 3.2.4 on 2021-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0063_alter_timewebmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='tag_position',
            field=models.CharField(choices=[('Left', 'Left'), ('Middle', 'Middle'), ('Right', 'Right')], default='Middle', max_length=6),
        ),
    ]
