# Generated by Django 3.2.4 on 2021-07-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0064_settingsmodel_tag_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='warning_acceptance',
        ),
    ]
