# Generated by Django 3.2.4 on 2021-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0065_remove_settingsmodel_warning_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
    ]
