# Generated by Django 3.2.4 on 2021-08-18 06:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0067_alter_settingsmodel_def_unit_to_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_break_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=13, null=True, verbose_name='Default Break Days'),
        ),
    ]
