# Generated by Django 3.2.4 on 2021-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0068_alter_settingsmodel_def_break_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='tag_position',
            field=models.CharField(choices=[('Left', 'Left'), ('Middle', 'Middle'), ('Right', 'Right')], default='Middle', max_length=6, verbose_name='Assignment Tag Position'),
        ),
    ]
