# Generated by Django 3.2.4 on 2021-08-18 06:45

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0069_alter_settingsmodel_tag_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=timewebapp.models.create_image_path, verbose_name='Background Image'),
        ),
    ]
