# Generated by Django 3.2.4 on 2021-09-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0070_alter_settingsmodel_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='ctime',
            new_name='time_per_unit',
        ),
    ]
