# Generated by Django 3.2.4 on 2021-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0071_rename_ctime_timewebmodel_time_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='tag_position',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='horizontal_tag_position',
            field=models.CharField(choices=[('Left', 'Left'), ('Middle', 'Middle'), ('Right', 'Right')], default='Middle', max_length=6, verbose_name='Horizontal Assignment Tag Position'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='vertical_tag_position',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', max_length=6, verbose_name='Vertical Assignment Tag Position'),
        ),
    ]
