# Generated by Django 3.2.7 on 2021-09-19 07:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0072_auto_20210905_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='is_google_classroom_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='time_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), "This field's value must be positive")]),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='unit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name of each Unit of Work'),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
        migrations.AlterField(
            model_name='timewebmodel',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1, "This field's value can't be less than %(limit_value)s")]),
        ),
    ]
