# Generated by Django 3.2.7 on 2021-09-19 17:46

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0073_auto_20210919_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='works',
            field=models.JSONField(blank=True, default=timewebapp.models.list_with_zero),
        ),
    ]
