# Generated by Django 3.2.7 on 2021-09-30 23:11

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0077_settingsmodel_default_dropdown_assignment_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='default_dropdown_assignment_tags',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='default_dropdown_tags',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list, verbose_name='Default Dropdown Tags'),
        ),
    ]
