# Generated by Django 3.2.7 on 2021-10-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0078_auto_20210930_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='reverse_sorting',
            field=models.BooleanField(default=False, verbose_name='Sort Assignments in Reverse'),
        ),
    ]
