# Generated by Django 3.2.7 on 2021-10-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0079_settingsmodel_reverse_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='soft',
            field=models.BooleanField(default=False),
        ),
    ]
