# Generated by Django 3.2.7 on 2021-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0080_timewebmodel_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='has_alerted_due_date_passed_notice',
            field=models.BooleanField(default=False),
        ),
    ]
