# Generated by Django 3.2.7 on 2021-11-04 05:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0082_settingsmodel_assignment_spacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='highest_priority_color',
            field=colorfield.fields.ColorField(default='#e8564a', max_length=18, verbose_name='Highest Priority Color'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='lowest_priority_color',
            field=colorfield.fields.ColorField(default='#84d336', max_length=18, verbose_name='Lowest Priority Color'),
        ),
    ]
