# Generated by Django 3.2.7 on 2021-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0083_auto_20211103_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='seen_latest_changelog',
            field=models.BooleanField(default=True),
        ),
    ]
