# Generated by Django 3.2.7 on 2021-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0084_settingsmodel_seen_latest_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_progress_bar',
            field=models.BooleanField(default=True, verbose_name='Show Graph Progress Bar'),
        ),
    ]
