# Generated by Django 3.2.7 on 2021-11-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0085_alter_settingsmodel_show_progress_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='close_graph_after_work_input',
            field=models.BooleanField(default=False, verbose_name='Close Graph After Submitting Work Input'),
        ),
    ]
