# Generated by Django 3.2.7 on 2021-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0090_alter_timewebmodel_funct_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='one_graph_at_a_time',
            field=models.BooleanField(default=False, verbose_name='Allow only One Open Graph at a Time'),
        ),
    ]
