# Generated by Django 3.2.7 on 2021-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0091_settingsmodel_one_graph_at_a_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='restore_gc_assignments',
            field=models.BooleanField(default=False, verbose_name='Restore Deleted Google Classroom Assignments'),
        ),
    ]
