# Generated by Django 3.2.7 on 2021-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0092_settingsmodel_restore_gc_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='one_graph_at_a_time',
            field=models.BooleanField(default=False, verbose_name='Allow Only one open Graph at a Time'),
        ),
    ]
