# Generated by Django 3.2.7 on 2021-11-23 02:47

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0093_alter_settingsmodel_one_graph_at_a_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='def_due_time',
            field=models.TimeField(default=timewebapp.models.get_midnight_time, verbose_name='Default Due Time'),
        ),
    ]
