# Generated by Django 3.2.7 on 2021-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0094_settingsmodel_def_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_skew_ratio',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=17, verbose_name='Default Curvature'),
        ),
    ]
