# Generated by Django 3.2.7 on 2021-12-04 00:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0095_alter_settingsmodel_def_skew_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebmodel',
            name='break_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=13, null=True, verbose_name='Working Days'),
        ),
    ]
