# Generated by Django 3.2.7 on 2021-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0097_alter_timewebmodel_funct_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='use_in_progress',
            field=models.BooleanField(default=False, verbose_name='Enter Work inputs In-Place after Today'),
        ),
    ]
