# Generated by Django 3.2.7 on 2021-12-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0100_alter_settingsmodel_animation_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='animation_speed',
            field=models.CharField(choices=[('1', 'Normal (1x)'), ('0.5', 'Fast (2x)'), ('0', 'None (No animation)')], default='Normal', max_length=19, verbose_name='Animation Speed'),
        ),
    ]
