# Generated by Django 3.2.7 on 2021-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0103_alter_settingsmodel_def_break_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='show_advanced_controls',
            field=models.BooleanField(default=True, verbose_name='Show Advanced Controls'),
        ),
    ]
