# Generated by Django 3.2.7 on 2021-12-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0104_settingsmodel_show_advanced_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_advanced_controls',
            field=models.BooleanField(default=True, verbose_name='Show "Advanced Controls" beneath the Graph'),
        ),
    ]
