# Generated by Django 3.2.7 on 2021-12-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0105_alter_settingsmodel_show_advanced_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewebmodel',
            name='has_alerted_due_date_increment_notice',
            field=models.BooleanField(default=False),
        ),
    ]
