# Generated by Django 3.2.7 on 2021-12-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0107_rename_has_alerted_due_date_increment_notice_timewebmodel_has_alerted_due_date_incremented_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timewebmodel',
            old_name='has_alerted_due_date_incremented_notice',
            new_name='alert_due_date_incremented',
        ),
    ]
