# Generated by Django 3.2.10 on 2021-12-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0109_settingsmodel_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='reverse_sorting',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='assignment_sorting',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Reversed', 'Reversed'), ('Tag Name', 'Tag Name'), ('Tag Name Reversed', 'Tag Name Reversed')], default='Normal', max_length=17, verbose_name='Assignment Sorting: '),
        ),
    ]
