# Generated by Django 3.2.10 on 2021-12-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0110_auto_20211226_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='assignment_sorting',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Reversed', 'Reversed'), ('Tag Name', 'Tag Name')], default='Normal', max_length=8, verbose_name='Assignment Sorting: '),
        ),
    ]
