runtime: python39
default_expiration: "1m"
entrypoint: gunicorn -b :$PORT timeweb.wsgi
handlers:
  # This configures Google App Engine to serve the files in the app's static directory
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app
  - url: /.*
    secure: always
    script: auto
includes:
  # gitignored file with sensitive information
  - env_variables.yaml


#inbound_services:
#- mail