[phases.setup]
nixPkgs = ['python3']

[phases.install]
cmds = ['python -m venv /opt/venv', '. /opt/venv/bin/activate', 'pip install -r requirements.txt']

[start]
cmd = 'python manage.py migrate && gunicorn -b 0.0.0.0:$PORT --max-requests 1000 --workers 5 --threads 2 timeweb.wsgi'