# Generated by Django 4.0.6 on 2022-07-14 10:52

from django.db import migrations, models
import timewebauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('timewebauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewebuser',
            name='username',
            field=models.CharField(max_length=150, validators=[timewebauth.models.LabeledUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
