# Generated by Django 3.2.12 on 2022-04-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='def_funct_round_minute',
        ),
    ]
