# Generated by Django 3.2.13 on 2022-05-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_rename_dark_mode_settingsmodel_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='appearance',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('light', 'Light Mode'), ('dark', 'Dark Mode'), ('fancy dark', '𝐹𝒶𝓃𝒸𝓎 Dark Mode')], default='automatic', max_length=15, verbose_name='Appearance'),
        ),
    ]
