# Generated by Django 3.2.13 on 2022-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_alter_settingsmodel_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='appearance',
            field=models.CharField(choices=[('automatic', 'Sync with device'), ('light', 'Light Mode'), ('dark', 'Dark Mode'), ('fancy dark', '𝐹𝒶𝓃𝒸𝓎 Dark Mode')], default='automatic', max_length=16, verbose_name='Appearance'),
        ),
    ]
