# Generated by Django 3.2.13 on 2022-07-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_alter_settingsmodel_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='restore_gc_assignments',
        ),
    ]
