# Generated by Django 3.2.14 on 2022-07-10 09:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_remove_settingsmodel_restore_gc_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='swapping_animation_threshold',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0, "This setting can't be a negative number")], verbose_name='Swapping Animation Threshold'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='def_min_work_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), "This setting can't be a negative number")], verbose_name='Default Minimum Daily Work Time'),
        ),
    ]
