# Generated by Django 4.0.6 on 2022-07-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0008_auto_20220710_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='def_due_time',
        ),
    ]
