# Generated by Django 4.0.6 on 2022-07-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0009_remove_settingsmodel_def_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='hide_completely_finished_assignments',
            field=models.BooleanField(default=False, verbose_name='Hide Completely Finished Assignments'),
        ),
    ]
