# Generated by Django 3.2.13 on 2022-07-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0010_settingsmodel_hide_completely_finished_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='hide_completely_finished_assignments',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='immediately_delete_completely_finished_assignments',
            field=models.BooleanField(default=False, verbose_name='Instantly Delete Completely Finished Assignments'),
        ),
    ]
