# Generated by Django 3.2.13 on 2022-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0011_auto_20220720_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='immediately_delete_completely_finished_assignments',
            field=models.BooleanField(default=False, verbose_name='Immediately Delete Completely Finished Assignments'),
        ),
    ]
