# Generated by Django 4.0.6 on 2022-08-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0012_alter_settingsmodel_immediately_delete_completely_finished_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='ignore_ends',
            new_name='loosely_enforce_minimum_work_times',
        ),
    ]
