# Generated by Django 4.0.6 on 2022-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0013_rename_ignore_ends_settingsmodel_loosely_enforce_minimum_work_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='loosely_enforce_minimum_work_times',
            field=models.BooleanField(default=False, verbose_name='Loosely Enforce Minimum Work Times'),
        ),
    ]
