# Generated by Django 4.0.6 on 2022-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0014_alter_settingsmodel_loosely_enforce_minimum_work_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='appearance',
            field=models.CharField(choices=[('automatic', 'Sync with device'), ('light', 'Light Mode'), ('fancy dark', '𝐹𝒶𝓃𝒸𝓎 Dark Mode')], default='automatic', max_length=16, verbose_name='Appearance'),
        ),
    ]
