# Generated by Django 4.0.6 on 2022-08-28 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0016_alter_settingsmodel_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='sorting_animation_threshold',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0, "This setting can't be a negative number")], verbose_name='Sorting Animation Threshold'),
        ),
    ]
