# Generated by Django 4.0.7 on 2022-09-21 21:18

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0018_settingsmodel_nudge_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='gc_courses_cache',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
    ]
