# Generated by Django 4.0.7 on 2022-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0025_alter_settingsmodel_assignment_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='assignment_sorting',
            field=models.CharField(choices=[('Most Priority First', 'Most Priority First'), ('Least Priority First', 'Least Priority First'), ('Most Work Today First', 'Most Work Today First'), ('Soonest Due Date First', 'Soonest Due Date First'), ('Tag Name A-Z', 'Tag Name A-Z'), ('Tag Name Z-A', 'Tag Name Z-A')], default='Normal', max_length=22, verbose_name='Assignment Sorting: '),
        ),
    ]
