# Generated by Django 4.0.7 on 2022-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0027_alter_settingsmodel_assignment_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
