# Generated by Django 4.0.7 on 2022-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0028_settingsmodel_device_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='device_uuid_save_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
