# Generated by Django 4.0.7 on 2022-12-23 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0030_rename_device_uuid_save_time_settingsmodel_device_uuid_api_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='device_uuid_api_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
