# Generated by Django 4.0.7 on 2023-01-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0033_alter_settingsmodel_display_working_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='animation_speed',
            field=models.CharField(choices=[('1', 'Normal (1x)'), ('0.5', 'Fast (2x)'), ('0', 'None (No animation)')], default='1', max_length=3, verbose_name='Animation Speed'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='appearance',
            field=models.CharField(choices=[('automatic', 'Sync with device'), ('light', 'Light Mode'), ('dark', 'Dark Mode'), ('lesser dark', 'Lesser Dark Mode')], default='automatic', max_length=11, verbose_name='Appearance'),
        ),
    ]
