# Generated by Django 4.0.7 on 2023-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0034_alter_settingsmodel_animation_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='background_image_text_shadow_width',
            field=models.CharField(choices=[('none', 'None'), ('normal', 'Normal'), ('thick', 'Thick')], default='normal', max_length=6, verbose_name='Background Image Text Shadow Width'),
        ),
    ]
