# Generated by Django 4.0.7 on 2023-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0035_settingsmodel_background_image_text_shadow_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='background_image_text_shadow_width',
            field=models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('normal', 'Normal'), ('thick', 'Thick')], default='normal', max_length=6, verbose_name='Background Image Text Shadow Width'),
        ),
    ]
