# Generated by Django 4.0.8 on 2023-01-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0036_alter_settingsmodel_background_image_text_shadow_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='background_image_text_shadow_width',
            field=models.CharField(choices=[('none', 'None'), ('thin', 'Thin'), ('normal', 'Normal'), ('thick', 'Thick')], default='normal', max_length=6, verbose_name='Background Image Text Shadow Width'),
        ),
    ]
