# Generated by Django 4.0.8 on 2023-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0037_alter_settingsmodel_background_image_text_shadow_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='gc_assignments_always_midnight',
            field=models.BooleanField(default=False, verbose_name='Google Classroom 11:59 PM Due Time Fix'),
        ),
    ]
