# Generated by Django 4.0.8 on 2023-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0038_settingsmodel_gc_assignments_always_midnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='assignment_sorting',
            field=models.CharField(choices=[('Most Priority First', 'Most Priority First'), ('Least Priority First', 'Least Priority First'), ('Most Work Today First', 'Most Work Today First'), ('Least Work Today First', 'Least Work Today First'), ('Soonest Due Date First', 'Soonest Due Date First'), ('Tag Name A-Z', 'Tag Name A-Z'), ('Tag Name Z-A', 'Tag Name Z-A')], default='Most Priority First', max_length=22, verbose_name='Assignment Sorting: '),
        ),
    ]
