# Generated by Django 4.0.9 on 2023-02-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0039_alter_settingsmodel_assignment_sorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='timezone',
        ),
    ]
