# Generated by Django 4.1.7 on 2023-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0041_alter_settingsmodel_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='appearance',
            field=models.CharField(choices=[('automatic', 'Sync with device'), ('light', 'Light Mode'), ('dark', 'Dark Mode'), ('lesser dark', 'Lesser Dark Mode')], default='dark', max_length=11, verbose_name='Color Scheme'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_priority',
            field=models.BooleanField(default=True, verbose_name='Display Priority'),
        ),
    ]
