# Generated by Django 4.1.7 on 2023-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0042_alter_settingsmodel_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='priority_color_borders',
            field=models.BooleanField(default=False, verbose_name='Priority Color Borders'),
        ),
    ]
