# Generated by Django 4.1.7 on 2023-03-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0043_settingsmodel_priority_color_borders'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='font',
            field=models.CharField(choices=[('opensans', 'Open Sans'), ('montserrat', 'Montserrat')], default='opensans', max_length=10, verbose_name='Font'),
        ),
    ]
