# Generated by Django 4.1.7 on 2023-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0045_settingsmodel_should_alert_due_date_incremented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='should_alert_due_date_incremented',
            field=models.BooleanField(default=True, verbose_name='Alert Soft Due Date Incremented'),
        ),
    ]
