# Generated by Django 4.1.7 on 2023-05-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0021_alter_timewebmodel_name'),
        ('navbar', '0046_alter_settingsmodel_should_alert_due_date_incremented'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='example_assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timewebapp.timewebmodel'),
        ),
    ]
