# Generated by Django 4.1.7 on 2023-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0047_alter_settingsmodel_assignment_sorting'),
        ('navbar', '0047_settingsmodel_example_assignment'),
    ]

    operations = [
    ]
