# Generated by Django 4.1.9 on 2023-05-30 17:19

from django.db import migrations
import encrypted_json_fields.fields
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0048_merge_20230522_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='oauth_token',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, default=timewebapp.models.empty_dict),
        ),
    ]
