# Generated by Django 4.1.9 on 2023-05-31 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timewebapp', '0021_alter_timewebmodel_name'),
        ('navbar', '0049_alter_settingsmodel_oauth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='example_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timewebapp.timewebmodel'),
        ),
    ]
