# Generated by Django 4.1.9 on 2023-06-03 22:26

from django.db import migrations, models
import timewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0052_alter_settingsmodel_canvas_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='added_canvas_assignment_ids',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='canvas_courses_cache',
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
    ]
