# Generated by Django 4.1.9 on 2023-06-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0053_settingsmodel_added_canvas_assignment_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='oauth_token',
            new_name='gc_token',
        ),
    ]
