# Generated by Django 4.1.9 on 2023-06-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0054_rename_oauth_token_settingsmodel_gc_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='nudge_canvas',
        ),
    ]
