# Generated by Django 4.1.9 on 2023-06-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0055_remove_settingsmodel_nudge_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='canvas_instance_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
