# Generated by Django 4.1.9 on 2023-06-21 01:17

from django.db import migrations, models
import encrypted_json_fields.fields
import timewebapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("navbar", "0056_settingsmodel_canvas_instance_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsmodel",
            name="added_moodle_assignment_ids",
            field=models.JSONField(blank=True, default=timewebapp.models.empty_list),
        ),
        migrations.AddField(
            model_name="settingsmodel",
            name="moodle_instance_domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="settingsmodel",
            name="moodle_token",
            field=encrypted_json_fields.fields.EncryptedJSONField(
                blank=True, default=timewebapp.models.empty_dict
            ),
        ),
    ]
