# Generated by Django 4.1.9 on 2023-06-22 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navbar", "0057_settingsmodel_added_moodle_assignment_ids_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settingsmodel",
            old_name="moodle_instance_domain",
            new_name="moodle_instance_url",
        ),
    ]
