# Generated by Django 4.1.9 on 2023-06-22 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "navbar",
            "0058_rename_moodle_instance_domain_settingsmodel_moodle_instance_url",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="settingsmodel",
            old_name="canvas_instance_domain",
            new_name="canvas_instance_url",
        ),
    ]
