# Generated by Django 4.1.9 on 2023-06-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "navbar",
            "0059_rename_canvas_instance_domain_settingsmodel_canvas_instance_url",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsmodel",
            name="canvas_instance_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Canvas Home URL"
            ),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="moodle_instance_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Moodle Home URL"
            ),
        ),
    ]
